server:
  port: 9002
spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    driver-class-name: oracle.jdbc.OracleDriver
    username: ljg
    password: Aa1234567
  main:
    allow-bean-definition-overriding: true
  redis:
    cluster:
      nodes: 127.0.0.1:6379,127.0.0.1:6380,127.0.0.1:6381
    password:
    jedis:
      pool:
        max-wait: 5000
        max-idle: 50
        min-idle: 5
    timeout: 15000
eureka:
  client:
    service-url:
      defaultZone: http://135.64.99.122:8000/eureka/
zuul:
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 30000
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

